NoteListApp/Models/Diary.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NoteListApp.Models
{
    public class Diary
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string title { get; set; }
        public string description { get; set; }
        public DateTime date { get; set; }
    }
}

NoteListApp/Models/ErrorViewModel.cs
using System;

namespace NoteListApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NoteListApp/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NoteListApp.Models
{
    public class Note
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string name { get; set; }
        public string description { get; set; }
    }
}

NoteListApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NoteListApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace NoteListApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NoteListApp/Controllers/NoteController.cs
using Microsoft.AspNetCore.Mvc;
using NoteListApp.Data;
using NoteListApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NoteListApp.Controllers
{
    public class NoteController : Controller
    {
        private readonly ApplicationDbContext _db;

        public NoteController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Note> noteList = _db.Note;
            return View(noteList);
        }

        //GET-create
        public IActionResult Create()
        { 
            return View();
        }

        //POST-create
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(Note notes)
        {
            // server side validation
            if (ModelState.IsValid)
            {
                _db.Note.Add(notes);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(notes);
            
        }

        //GET-update
        public IActionResult Update(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var note = _db.Note.Find(id);
            if(note == null)
            {
                return NotFound();
            }
            return View(note);
        }

        //POST-update
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Update(Note notes)
        {
            // server side validation
            if (ModelState.IsValid)
            {
                _db.Note.Update(notes);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(notes);

        }

        //GET-delete
        public IActionResult Delete(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var note = _db.Note.Find(id);
            if (note == null)
            {
                return NotFound();
            }
            return View(note);
        }

        //POST-delete
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Deleted(int id)
        {
            var notes = _db.Note.Find(id);
            if(notes == null)
            {
                return NotFound();
            }
            _db.Note.Remove(notes);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

NoteListApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" style="color:white">
    <h1 class="display-4">Welcome</h1>
    <p>Made with <a href="https://docs.microsoft.com/aspnet/core"> ASP.NET Core</a>.</p
    <p>and deployed on <a href="https://azure.microsoft.com/en-us/">Azure Services</a></p>
</div>

NoteListApp/Views/Note/Create.cshtml
@model NoteListApp.Models.Note

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @*<div asp-validation-summary="All" class="text-danger"></div>*@

        <div class="form-group row">
            <h1 class="text-warning pl-3">Add Category</h1>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="name" style="color:ghostwhite;font-weight:700">Name</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="name" class="form-control" />
                        <span asp-validation-for="name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="description" style="color:ghostwhite;font-weight:700">Description</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="description" class="form-control" />
                        <span asp-validation-for="description" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-warning w-100"><i class="fas fa-sign-out-alt"></i> Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@*client side validation*@
@section Scripts
{
 <partial name="_ValidationScriptsPartial" />
} 

NoteListApp/Views/Note/Delete.cshtml
@model NoteListApp.Models.Note

<form method="post" asp-action="Deleted">
    @*must have to update as it needs the ID*@
    <input asp-for="ID" hidden />

    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        @*<div asp-validation-summary="All" class="text-danger"></div>*@

        <div class="form-group row">
            <h1 class="text-danger pl-3">Delete Category</h1>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="name" style="color:ghostwhite;font-weight:700">Name</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="name" class="form-control" disabled/>
                        <span asp-validation-for="name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="description" style="color:ghostwhite;font-weight:700">Description</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="description" class="form-control" disabled/>
                        <span asp-validation-for="description" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-warning w-100"><i class="fas fa-sign-out-alt"></i> Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

NoteListApp/Views/Note/Index.cshtml
@model IEnumerable<NoteListApp.Models.Note>

<div class="container p-4">
    <div class="row p-4">
        <div class="h1 col" style="color:whitesmoke">Note List</div>
        <div class="col text-right">
            <button type="button" class="btn btn-success">
                <a style="color:white;text-decoration:none" asp-controller="Note" asp-action="Create">Add Note</a> 
            </button>
        </div>
    </div>
</div>

<br />

@if (Model.Count() > 0)
            {
                <table class="table table-bordered">
                    <thead >
                        <tr class="table-info">
                            <th scope="col">Name</th>
                            <th scope="col">Description</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var list in Model)
                        {
                            <tr>
                                <td width="35%" class="table-light">@list.name</td>
                                <td width="35%" class="table-light">@list.description</td>
                                <td width="30%" class="table-warning">
                                    <div class="row p-2 justify-content-center">
                                        <a asp-controller="Note" asp-action="Update" asp-route-id="@list.ID" class="col p-2 btn btn-warning">Edit</a>
                                        <a asp-controller="Note" asp-action="Delete" asp-route-id="@list.ID" class="col p-2 btn btn-danger">Delete</a>
                                    </div>
                                    
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }

NoteListApp/Views/Note/Update.cshtml
@model NoteListApp.Models.Note

<form method="post" asp-action="Update">
    @*must have to update as it needs the ID*@
    <input asp-for="ID" hidden />

    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        @*<div asp-validation-summary="All" class="text-danger"></div>*@

        <div class="form-group row">
            <h1 class="text-warning pl-3">Edit Category</h1>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="name" style="color:ghostwhite;font-weight:700">Name</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="name" class="form-control" />
                        <span asp-validation-for="name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="description" style="color:ghostwhite;font-weight:700">Description</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="description" class="form-control" />
                        <span asp-validation-for="description" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Edit" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-warning w-100"><i class="fas fa-sign-out-alt"></i> Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

NoteListApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NoteListApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="bg-img">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NoteListApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="Index">Note</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NoteListApp - 
            @*<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
            <a href="https://github.com/chairielazizi" >Chairiel Azizi</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>